[project]
name = "level-1"
version = "0.1.0"
description = "Coded By Kaali!"
readme = "README.md"
authors = [
    { name = "kaali", email = "akshaydaisuke@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "bcrypt>=5.0.0",
    "fastapi[standard]>=0.141.1",
    "psycopg2-binary>=2.9.13",
    "sqlalchemy>=2.0.53",
]

[project.scripts]
level-1 = "level_1:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
